version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: mypostgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sonarqube
    networks:
      - sonarqube_community_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mypgadmin
    restart: always
    ports:
      - "8081:80/tcp"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres
    networks:
      - sonarqube_community_network

  sonarqube:
    image: sonarqube:latest
    container_name: mysonarqube
    restart: always
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=admin
      - SONARQUBE_JDBC_URL=jdbc:postgresql://mypostgres:5432/sonarqube
      - SONAR_ES_JAVA_OPTS=-Xms512m -Xmx512m
    depends_on:
      - postgres
    networks:
      - sonarqube_community_network

networks:
  sonarqube_community_network:
    driver: bridge
    ipam:
      driver: default
