version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "80:80/tcp"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres
