version: "3.8"
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=biblioteca
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin123

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "90:80/tcp"
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=admin123