version: '3.8'
services:
  kali-linux:
    image: kalilinux/kali-rolling:latest
    container_name: my-kali
    restart: always
    tty: true
    stdin_open: true
    user: root
    ports:
      - "8020:80"
    volumes:
      - C:\Users\bismarck.colombo\docker_kali:/var/www/html
